
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "3311:5000"
    environment:
      - NODE_ENV=development
    command: npm run dev 
